# Data Mining в середовищі Pandas

### ТЕОРЕТИЧНА ЧАСТИНА ТА ПРИКЛАДИ

Для роботи з структурованими табличними даними на мові Python розроблено [бібліотеку __Pandas__](https://ru.wikipedia.org/wiki/Pandas)
- [Офіційний сайт](https://pandas.pydata.org)
- [Сайт на GitHub](https://github.com/pandas-dev/pandas)

In [3]:
!pwd

/Users/sergey/Google Диск/Учебный процесс 2022-23/1 СЕМЕСТР/МАГІСТРИ - ТПОЗІС/DM-2023/Лабораторна №5

In [1]:
# підключення бібліотеки з аліасом/псевдонімом 'pd'
import pandas as pd

In [ ]:
print(dir(pd))

#### ПРИКЛАД ЗАВАНТАЖЕННЯ ДАНИХ В Pandas з ЗОВНІШНІХ ДЖЕРЕЛ
Створити в Pandas датасет з ім'ям `jornal`, та завантажити в нього csv-файл, що містить журнал групи `Jornal.csv`

In [24]:
# створюємо датасет та завантажуємо в нього csv-файл 
jornal = pd.read_csv('Jornal.csv')

In [25]:
type(jornal)

pandas.core.frame.DataFrame

##### виведемо ВСІ записи датасету `jornal`

In [27]:
jornal.head()

,Surname,Name,email,GitHub
0,Антонов,Іван,i.antonov_fit_4m_22_m_d@knute.edu.ua,NaN
1,Антонюк,Данило,d.antonyuk_fit_4m_22_m_d@knute.edu.ua,NaN
2,Багінський,Вадим,v.bahinskyy_fit_4m_22_m_d@knute.edu.ua,NaN
3,Бай,Андрій,a.bay_fit_4m_22_m_d@knute.edu.ua,https://github.com/Ullrvetr
4,Безсмертний,Володимир,v.bezsmertnyy_fit_4m_22_m_d@knute.edu.ua,NaN

#### ПРИКЛАД ЗБАГАЧЕННЯ ДАНИХ 

Додати до журналу оцінки за вступне тестування, які розташовані в csv файлі `test_result.csv`

In [28]:
# створимо датасет з результатами тестів
test_result = pd.read_csv('test_result.csv')

In [30]:
test_result

       Surname  test
0   Багінський    63
1          Бай    51
2     Власенко    52
3        Гелла    82
4      Гонгало    44
5      Копотун    44
6     Коротких    69
7       Красюк    53
8     Ластовка    77
9   Мартиненко    68
10    Масовець    78
11      Мовчан    52
12     Силенко    74
13       Стась    66
14        Стус    56
15        Ткач    54
16   Устименко    35
17    Якименко    47

In [31]:
# переіменуємо робочі поля для зручності
test_result.rename(columns={"Surname": "Name", "test": "Rate"}, inplace=True)

##### Cтворимо новий датасет `jornal_test`, який буде містити вміст датасету `jornal` та колонку оцінок з  `test_result`

In [32]:
jornal.merge?

In [33]:
# виконаємо поєднання через метод 'merge':
#   лівий дадатсет - беремо всі колонки з 'jornal'
#   правий датасет - беремо дві колонки з 'test_result'

jornal_test = jornal.merge(test_result[["Name", "Rate"]], 
                           left_on="Surname", right_on="Name", how='left')

In [34]:
jornal_test

,Surname,Name_x,email,GitHub,Name_y,Rate
0,Антонов,Іван,i.antonov_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
1,Антонюк,Данило,d.antonyuk_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
2,Багінський,Вадим,v.bahinskyy_fit_4m_22_m_d@knute.edu.ua,NaN,Багінський,63.0
3,Бай,Андрій,a.bay_fit_4m_22_m_d@knute.edu.ua,https://github.com/Ullrvetr,Бай,51.0
4,Безсмертний,Володимир,v.bezsmertnyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
5,Будяну,Максим,m.budyanu_fit_4m_22_m_d@knute.edu.ua,https://github.com/Budeanu,NaN,NaN
6,Власенко,Олександр,o.vlasenko_fit_4m_22_m_d@knute.edu.ua,NaN,Власенко,52.0
7,Гелла,Всеволод,v.hella_fit_4m_22_m_d@knute.edu.ua,NaN,Гелла,82.0
8,Гонгало,Вадим,v.honhalo_fit_4m_22_m_d@knute.edu.ua,https://github.com/Vaditos/DM--honhalo-,Гонгало,44.0
9,Дринь,Ярослав,y.dryn_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
10,Дубовий,Іван,i.dubovyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
11,Копотун,Світлана,s.kopotun_fit_4m_22_m_d@knute.edu.ua,https://github.com/Kopotuns,Копотун,44.0
12,Коротких,Віталій,v.korotkykh_fit_4m_22_m_d@knute.edu.ua,NaN,Коротких,69.0
13,Красюк,Олександр,o.krasyuk_fit_4m_22_m_d@knute.edu.ua,NaN,Красюк,53.0
14,Ластовка,Євген,y.lastovka_fit_4m_22_m_d@knute.edu.ua,https://github.com/Pro7Za/DM-y.lastovka.git,Ластовка,77.0
15,Левицький,Владислав,v.levytskyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
16,Мартиненко,Дмитро,d.martynenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/Juvaily/DM-martynenko,Мартиненко,68.0
17,Масовець,Олександр,o.masovets_fit_4m_22_m_d@knute.edu.ua,https://github.com/viceblond/DM-masovets,Масовець,78.0
18,Мовчан,Єлизавета,y.movchan_fit_4m_22_m_d@knute.edu.ua,https://github.com/m-ellizabeth/DM_Movchan.git,Мовчан,52.0
19,Павлюк,Владислав,v.pavlyuk_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
20,Пивоваров,Владислав,v.pyvovarov_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
21,Постоленко,Олександр,o.postolenko_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN
22,Силенко,Олександр,o.sylenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/Onlinemirror/DM_sylenko_1m4...,Силенко,74.0
23,Стась,Олександр,o.stas_fit_4m_22_m_d@knute.edu.ua,https://github.com/OldWorldBIues/DM-stas,Стась,66.0
24,Стус,Олег,o.stus_fit_4m_22_m_d@knute.edu.ua,NaN,Стус,56.0
25,Ткач,Дмитро,d.tkach_fit_4m_22_m_d@knute.edu.ua,https://github.com/DmytroYuriyovych/DM_TkachDm...,Ткач,54.0
26,Устименко,Назар,n.ustymenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/ustymenk0/DM-ustymenko.git,Устименко,35.0
27,Якименко,Владислав,v.yakymenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/vladeeek/DM-v.yakymenko-2-,Якименко,47.0
28,Яцуненко,Ростислав,r.yatsunenko_fit_4m_22_m_d@knute.edu.ua,NaN,NaN,NaN

In [35]:
# приведемо датасет до виду для подальшого аналізу:
#   - змінемо ім'я колонки 'Name_x' на 'Name'
#   - видалимо зайву колонку 'Name_y'
#   - відсортеруємо по колонці 'Surname'

jornal_test = jornal_test.rename(columns={"Name_x": "Name"}) \
                         .drop(columns="Name_y")             \
                         .sort_values("Surname", axis=0)

In [36]:
jornal_test

,Surname,Name,email,GitHub,Rate
0,Антонов,Іван,i.antonov_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
1,Антонюк,Данило,d.antonyuk_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
2,Багінський,Вадим,v.bahinskyy_fit_4m_22_m_d@knute.edu.ua,NaN,63.0
3,Бай,Андрій,a.bay_fit_4m_22_m_d@knute.edu.ua,https://github.com/Ullrvetr,51.0
4,Безсмертний,Володимир,v.bezsmertnyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
5,Будяну,Максим,m.budyanu_fit_4m_22_m_d@knute.edu.ua,https://github.com/Budeanu,NaN
6,Власенко,Олександр,o.vlasenko_fit_4m_22_m_d@knute.edu.ua,NaN,52.0
7,Гелла,Всеволод,v.hella_fit_4m_22_m_d@knute.edu.ua,NaN,82.0
8,Гонгало,Вадим,v.honhalo_fit_4m_22_m_d@knute.edu.ua,https://github.com/Vaditos/DM--honhalo-,44.0
9,Дринь,Ярослав,y.dryn_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
10,Дубовий,Іван,i.dubovyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
11,Копотун,Світлана,s.kopotun_fit_4m_22_m_d@knute.edu.ua,https://github.com/Kopotuns,44.0
12,Коротких,Віталій,v.korotkykh_fit_4m_22_m_d@knute.edu.ua,NaN,69.0
13,Красюк,Олександр,o.krasyuk_fit_4m_22_m_d@knute.edu.ua,NaN,53.0
14,Ластовка,Євген,y.lastovka_fit_4m_22_m_d@knute.edu.ua,https://github.com/Pro7Za/DM-y.lastovka.git,77.0
15,Левицький,Владислав,v.levytskyy_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
16,Мартиненко,Дмитро,d.martynenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/Juvaily/DM-martynenko,68.0
17,Масовець,Олександр,o.masovets_fit_4m_22_m_d@knute.edu.ua,https://github.com/viceblond/DM-masovets,78.0
18,Мовчан,Єлизавета,y.movchan_fit_4m_22_m_d@knute.edu.ua,https://github.com/m-ellizabeth/DM_Movchan.git,52.0
19,Павлюк,Владислав,v.pavlyuk_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
20,Пивоваров,Владислав,v.pyvovarov_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
21,Постоленко,Олександр,o.postolenko_fit_4m_22_m_d@knute.edu.ua,NaN,NaN
22,Силенко,Олександр,o.sylenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/Onlinemirror/DM_sylenko_1m4...,74.0
23,Стась,Олександр,o.stas_fit_4m_22_m_d@knute.edu.ua,https://github.com/OldWorldBIues/DM-stas,66.0
24,Стус,Олег,o.stus_fit_4m_22_m_d@knute.edu.ua,NaN,56.0
25,Ткач,Дмитро,d.tkach_fit_4m_22_m_d@knute.edu.ua,https://github.com/DmytroYuriyovych/DM_TkachDm...,54.0
26,Устименко,Назар,n.ustymenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/ustymenk0/DM-ustymenko.git,35.0
27,Якименко,Владислав,v.yakymenko_fit_4m_22_m_d@knute.edu.ua,https://github.com/vladeeek/DM-v.yakymenko-2-,47.0
28,Яцуненко,Ростислав,r.yatsunenko_fit_4m_22_m_d@knute.edu.ua,NaN,NaN

#### ПРИКЛАД  ДЕСКРИПТИВНОГО АНАЛІЗУ ДАНИХ

Провести [попередній аналіз](https://ru.wikipedia.org/wiki/Описательная_статистика) отриманих даних з ціллю виявленя відхилень, помилок та інших непридатних даних.

Сведемо результати аналізу в таблицю, яка має наступний вигляд:

№| Показчик | Значення
:--:|:-------|-------:
1| кількість спостережень | xx 
2| кількість пустих значень | xx
4| середній бал|  xx.x
5| максимальний бал | xx
6| мінімальний бал  | xx
7| стандартне відхилення | xx.x
8| розмах вариації  | xx

In [37]:
jornal_test.describe()

            Rate
count  18.000000
mean   59.166667
std    13.474377
min    35.000000
25%    51.250000
50%    55.000000
75%    68.750000
max    82.000000

In [38]:
# сведемо розрахункові показчики у 2-мірну матрицю
values = [
    ["Кількість спостережень",   jornal_test.count()["Surname"]],
    ["Кількість пустих значень", jornal_test.count()["Rate"]],
    ["Середній бал",             jornal_test.mean()["Rate"]],
    ["Максимальний бал",         jornal_test.max()["Rate"]],
    ["Мінімальний бал",          jornal_test.max()["Rate"]],
    ["Стандартне відхилення",    jornal_test.std()["Rate"]],
    ["Розмах вариації",          jornal_test.max()["Rate"] - jornal_test.min()["Rate"]]
]

In [41]:
values

[['Кількість спостережень', 29],
 ['Кількість пустих значень', 18],
 ['Середній бал', 59.166666666666664],
 ['Максимальний бал', 82.0],
 ['Мінімальний бал', 82.0],
 ['Стандартне відхилення', 13.474376554386915],
 ['Розмах вариації', 47.0]]

In [42]:
# будуємо результатний датасет
result = pd.DataFrame( data=values, columns=["Показчик", "Значення"], dtype='object')

In [43]:
result

                   Показчик   Значення
0    Кількість спостережень         29
1  Кількість пустих значень         18
2              Середній бал  59.166667
3          Максимальний бал       82.0
4           Мінімальний бал       82.0
5     Стандартне відхилення  13.474377
6           Розмах вариації       47.0

### ІНДИВІДУАЛЬНЕ ЗАВДАННЯ

Користуючись результатами, що отримані в [Лабораторній роботі № 3](https://shkliarskiy.moodlecloud.com/mod/page/view.php?id=1193) виконати процедури видобутку, збагачення та попереднього аналізу даних за допомогою ббліотеки __Pandas__.

__Постановка__: В 3-й лабораторній роботі отримано показчик, що характеризує окрему властивість квартири (ціна, метраж та ін.). 
Необхідно:
1. Створити pandas-датасет з файлу `aprt_properties.csv`, який містить всі показчики квартир 
2. Прив'язати цей датасет до датасету з розбивкою вулиць по районам
3. Отримати сводний датасет у вигляді (*приклад*):
<img src='result_img.png' width=600px>

In [2]:
# імпортувати бібліотеку Pandas
import pandas as pd
import numpy as np

In [3]:
# створирти датасет 'aprt_properties' з файлу 'aprt_properties.csv'
aprt_properties = pd.read_csv('aprt_properties.csv')

In [4]:
# вивести перші десять рядків датасету
aprt_properties.head(10)

,Price,rooms,price_per_m2,level,levels,year,area_total,area_living,area_kitchen,street,publish_date
0,140000.0,2,2258.0,7,9,1969,62.0,47.0,9.0,Омеляновича-Павленка,3 вересня 2020 р.
1,105000.0,4,847.0,25,26,2018,124.0,71.0,16.0,NaN,7 жовтня 2020 р.
2,175000.0,3,1786.0,25,26,2010,98.0,None,None,Ованеса Туманяна,1 жовтня 2020 р.
3,30970.0,1,1106.0,12,13,2013,28.0,13.0,5.0,Петропавлівська,1 лютого
4,82000.0,2,1281.0,18,26,None,64.0,None,None,Дніпровська,*** not found
5,168535.7,3,1872.6,4,9,1966,90.0,45.0,10.0,Саксаганського,28 жовтня 2020 р.
6,4500000.0,4,14610.0,18,21,2011,308.0,None,None,Івана Мазепи,19 жовтня 2020 р.
7,135000.0,2,2077.0,16,23,2012,65.0,25.0,18.0,Дніпровська,1 вересня 2020 р.
8,120000.0,1,2500.0,8,25,2012,48.0,18.0,16.0,Ділова,12 жовтня 2020 р.
9,57500.0,3,625.0,9,9,1970,92.0,None,None,Новодарницька,5 жовтня 2020 р.

In [17]:
# створити датасет 'reestr' з прив'язкою вуліць до районів з excel-файлу
# `Реєстр вулиць міста Києва-станом на 25-10-2020.xlsx`

# Оскільки даного файлу з реєстром у нас немає - створюємо новий засобами Pandas, використовуючи дані, які в наявності

import csv
nums = []
codes = []
streets = []
types = []
areas = []
docs = []
datas = []
doc_num = []
hdoc = []
ars = []
names = []
cats = []

num = 1
with open('kiev-districts.csv', 'r', encoding='utf-8') as file:
    reader = csv.reader(file, delimiter=',')
    for i in reader:
        if 'street' in i:
            pass
        else:
            nums.append(num)
            codes.append(None)
            streets.append(i[0])
            types.append(i[1])
            areas.append(i[2])
            docs.append(None)
            datas.append(None)
            doc_num.append(None)
            hdoc.append(None)
            ars.append(None)
            names.append(None)
            cats.append(None)
            num=num+1
df = pd.DataFrame({
    '№': nums,
    'код':codes,
    'Вулиця':streets,
    'тип':types,
    'Район':areas,
    'Документ':docs,
    'Дата документу':datas,
    'Номер документу':doc_num,
    'Заголовок документу':hdoc,
    'розташування':ars,
    'Найменування':names,
    'Категорія':cats,
})
df.to_excel('Реєстр вулиць міста Києва-станом на 25-10-2020.xlsx', index=False)

reestr = pd.read_excel('Реєстр вулиць міста Києва-станом на 25-10-2020.xlsx',
                       names= [
                                 '№',
                                 'код',
                                 'Вулиця',
                                 'тип',
                                 'Район',
                                 'Документ',
                                 'Дата документу',
                                 'Номер документу',
                                 'Заголовок документу',
                                 'розташування',
                                 'Найменування',
                                 'Категорія'
                       ],
                       header=None, skiprows=range(4), index_col=0)

In [18]:
type(None)

NoneType

In [19]:
type(np.nan)

float

In [20]:
# вивести 5 останніх рядків датасету `reestr`  
reestr.tail(5)

,код,Вулиця,тип,Район,Документ,Дата документу,Номер документу,Заголовок документу,розташування,Найменування,Категорія
№,,,,,,,,,,,
2839,NaN,Яслинська,вулиця,Солом'янський,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2840,NaN,Ясна,вулиця,Солом'янський,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2841,NaN,Ясний,провулок,Солом'янський,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,NaN,Ясногірська,вулиця,Шевченківський,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,NaN,Яснополянська,вулиця,Святошинський,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
aprt_properties.merge?

In [21]:
# приєднати райони з датасету 'reestr' до датасету 'aprt_properties'
# по загальному полю

street_district = aprt_properties.merge(reestr[['Вулиця', 'Район']], 
                                        left_on='street', right_on='Вулиця',
                                        how='left')

In [22]:
# вивести перші 10 рядків датасету 'street_district'
street_district.head(10)

,Price,rooms,price_per_m2,level,levels,year,area_total,area_living,area_kitchen,street,publish_date,Вулиця,Район
0,140000.0,2,2258.0,7,9,1969,62.0,47.0,9.0,Омеляновича-Павленка,3 вересня 2020 р.,NaN,NaN
1,105000.0,4,847.0,25,26,2018,124.0,71.0,16.0,NaN,7 жовтня 2020 р.,NaN,NaN
2,175000.0,3,1786.0,25,26,2010,98.0,None,None,Ованеса Туманяна,1 жовтня 2020 р.,NaN,NaN
3,30970.0,1,1106.0,12,13,2013,28.0,13.0,5.0,Петропавлівська,1 лютого,Петропавлівська,Оболонський
4,30970.0,1,1106.0,12,13,2013,28.0,13.0,5.0,Петропавлівська,1 лютого,Петропавлівська,Подільський
5,82000.0,2,1281.0,18,26,None,64.0,None,None,Дніпровська,*** not found,Дніпровська,Оболонський
6,168535.7,3,1872.6,4,9,1966,90.0,45.0,10.0,Саксаганського,28 жовтня 2020 р.,Саксаганського,"Голосіївський, Печерський, Шевченківський"
7,4500000.0,4,14610.0,18,21,2011,308.0,None,None,Івана Мазепи,19 жовтня 2020 р.,NaN,NaN
8,135000.0,2,2077.0,16,23,2012,65.0,25.0,18.0,Дніпровська,1 вересня 2020 р.,Дніпровська,Оболонський
9,120000.0,1,2500.0,8,25,2012,48.0,18.0,16.0,Ділова,12 жовтня 2020 р.,Ділова,"Голосіївський, Печерський"

In [23]:
# поліпшити якість датасету:

# - замінити `NaN`  району на ''
street_district["Район"] = street_district["Район"].fillna('') 

# - замінити список районів на перший
street_district["Район"] = street_district["Район"].str.split(',')
district_list = street_district["Район"].to_list()
district_list = [x[0] for x in district_list]
street_district["Район"] = pd.Series(district_list)

# - видалити дублюючі записи
street_district = street_district.drop_duplicates(subset=
                                ['Price', 'rooms', 'price_per_m2', 'level', 'levels'])

street_district.head(10)

,Price,rooms,price_per_m2,level,levels,year,area_total,area_living,area_kitchen,street,publish_date,Вулиця,Район
0,140000.0,2,2258.0,7,9,1969,62.0,47.0,9.0,Омеляновича-Павленка,3 вересня 2020 р.,NaN,
1,105000.0,4,847.0,25,26,2018,124.0,71.0,16.0,NaN,7 жовтня 2020 р.,NaN,
2,175000.0,3,1786.0,25,26,2010,98.0,None,None,Ованеса Туманяна,1 жовтня 2020 р.,NaN,
3,30970.0,1,1106.0,12,13,2013,28.0,13.0,5.0,Петропавлівська,1 лютого,Петропавлівська,Оболонський
5,82000.0,2,1281.0,18,26,None,64.0,None,None,Дніпровська,*** not found,Дніпровська,Оболонський
6,168535.7,3,1872.6,4,9,1966,90.0,45.0,10.0,Саксаганського,28 жовтня 2020 р.,Саксаганського,Голосіївський
7,4500000.0,4,14610.0,18,21,2011,308.0,None,None,Івана Мазепи,19 жовтня 2020 р.,NaN,
8,135000.0,2,2077.0,16,23,2012,65.0,25.0,18.0,Дніпровська,1 вересня 2020 р.,Дніпровська,Оболонський
9,120000.0,1,2500.0,8,25,2012,48.0,18.0,16.0,Ділова,12 жовтня 2020 р.,Ділова,Голосіївський
10,57500.0,3,625.0,9,9,1970,92.0,None,None,Новодарницька,5 жовтня 2020 р.,NaN,

In [24]:
# - замінити `NaN`  району на ''
street_district["Район"] = street_district["Район"].fillna('')

In [25]:
street_district["Район"] = street_district["Район"].str.split(',')

In [26]:
district_list = street_district["Район"].to_list()
district_list = [x[0] for x in district_list]
street_district["Район"] = pd.Series(district_list)

In [27]:
street_district = street_district.drop_duplicates(subset=
                                ['Price', 'rooms', 'price_per_m2', 'level', 'levels'])

In [28]:
street_district.tail(3)

,Price,rooms,price_per_m2,level,levels,year,area_total,area_living,area_kitchen,street,publish_date,Вулиця,Район
805,89000.0,1,2342.0,7,15,None,38.0,20.0,7.0,Перемоги,*** not found,Перемоги,NaN
808,170000.0,2,2656.0,5,7,1948,64.0,None,9.0,Велика Васильківська,6 березня 2019 р.,Велика Васильківська,NaN
810,46500.0,2,1011.0,5,5,1963,46.0,31.0,7.0,Вишгородська,24 лютого,Вишгородська,NaN

In [29]:
street_district[street_district['area_kitchen'] == 'None']

,Price,rooms,price_per_m2,level,levels,year,area_total,area_living,area_kitchen,street,publish_date,Вулиця,Район
2,175000.0,3,1786.0,25,26,2010,98.0,None,None,Ованеса Туманяна,1 жовтня 2020 р.,NaN,
5,82000.0,2,1281.0,18,26,None,64.0,None,None,Дніпровська,*** not found,Дніпровська,Голосіївський
7,4500000.0,4,14610.0,18,21,2011,308.0,None,None,Івана Мазепи,19 жовтня 2020 р.,NaN,Оболонський
10,57500.0,3,625.0,9,9,1970,92.0,None,None,Новодарницька,5 жовтня 2020 р.,NaN,Дарницький
15,125000.0,2,2778.0,6,9,1965,45.0,None,None,Виноградний,11 лютого,Виноградний,Голосіївський
...,...,...,...,...,...,...,...,...,...,...,...,...,...
776,73000.0,2,1000.0,21,25,None,73.0,None,None,Заболотного,*** not found,NaN,NaN
778,92284.0,2,1138.0,6,34,None,None,None,None,Заболотного,*** not found,NaN,NaN
780,139900.0,4,1260.0,6,9,None,111.0,None,None,Зарічна,*** not found,Зарічна,NaN
786,97926.0,1,1900.0,9,30,None,None,None,None,Драгомирова,*** not found,NaN,NaN
788,115000.0,3,1135.0,13,25,2004,None,None,None,Здолбунівська,22 листопада 2016 р.,Здолбунівська,NaN

In [30]:
street_district[street_district['area_kitchen'] == 'None'] = np.nan

In [31]:
# отримати сводний датасет по вашому показчику 
# ім'я показчика брати в лапки!

import numpy as np
result = street_district[[ 'Район', 'Price']]  \
      .groupby(['Район']) \
      .agg(Всього=('Price', 'count'),
           Макс=('Price', 'max'),
           Мін=('Price', 'min'),
           Ст_відх=('Price', 'std'),
           Середнє=('Price', 'mean'),
           Розмах=('Price', np.ptp)).round(2)

In [32]:
# вивести результат
result

                Всього        Макс      Мін     Ст_відх    Середнє      Розмах
Район
                   190  15700000.0  33000.0  1163260.30  239990.82  15667000.0
Голосіївський       36    620000.0  31000.0   157479.13  171060.49    589000.0
Дарницький          23    494000.0  38000.0   102846.74  142420.00    456000.0
Деснянський          6    347700.0  52000.0   114400.71  165783.33    295700.0
Дніпровський        17    177000.0  37000.0    46235.65   94309.41    140000.0
Оболонський         25    495000.0  30970.0   127702.01  120405.20    464030.0
Печерський          27   2100000.0  35000.0   411826.14  248596.04   2065000.0
Подільський         19    320000.0  36000.0    70266.48  115186.84    284000.0
Святошинський       15    612500.0  35600.0   149113.47  121999.93    576900.0
Солом'янський       13    480000.0  36000.0   115784.88  116584.62    444000.0
Шевченківський      29    777500.0  29900.0   168055.04  157415.62    747600.0